kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: px-postgres-sc
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "2"

---

##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: postgres-data
spec:
   storageClassName: px-postgres-sc
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 10Gi
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
data:
  EXAMPLE_DB_HOST: postgres://postgres@postgres/example?sslmode=disable
  EXAMPLE_DB_KIND: postgres
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin123

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: "postgres:10.1"
        name: postgres
        envFrom:
        - configMapRef:
            name: example-config
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data
---

apiVersion: v1
kind: Service
metadata:
  name: pg-service
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-counter-deployment
  labels:
    app: k8s-counter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-counter
  template:
    metadata:
      labels:
        app: k8s-counter
    spec:
      containers:
      - name: k8s-counter
        image: wallnerryan/moby-counter:k8s-record-count
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: USE_POSTGRES_HOST
          value: "pg-service"
        - name: USE_POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "admin123"

---

apiVersion: v1
kind: Service
metadata:
  name: k8s-counter-service
spec:
  type: NodePort
  selector:
    app: k8s-counter
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30123
    name: k8s-counter-web